'use strict';
const COLORS=['blue','green','red','black'];
const COLOR_NAMES={blue:'Blau',green:'Grün',red:'Rot',black:'Schwarz'};
const STARTS=[0,16,32,48];
const TEAM=[[0,2],[1,3]];
const CARD_LABEL={trick:'Trickser',tac:'TAC',angel:'Engel',devil:'Teufel',warrior:'Krieger',fool:'Narr'};
let state=null, selectedCard=null, modal=null;
const $=s=>document.querySelector(s);
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function makeDeck(){const d=[];[1,2,3,4,5,6,7,8,9,10,12,13].forEach(v=>{for(let i=0;i<8;i++)d.push({id:uid(),type:'num',value:v})});for(let i=0;i<2;i++){d.push({id:uid(),type:'trick'});d.push({id:uid(),type:'tac'})}['angel','devil','warrior','fool'].forEach(type=>d.push({id:uid(),type}));return shuffle(d)}
function fresh(names){return {version:1,names,players:COLORS.map((color,i)=>({color,hand:[],marbles:Array.from({length:4},(_,m)=>({id:i+'-'+m,owner:i,zone:'yard',pos:null,lap:false,locked:false}))})),deck:makeDeck(),discard:[],dealer:3,current:0,phase:'deal',dealNo:0,roundCards:0,exchange:{choices:{}},announcements:[],skip:false,history:[],lastAction:null,log:['Spiel wurde gestartet.'],winner:null}}
function save(){localStorage.setItem('kreistakt-save',JSON.stringify(state))}
function load(){try{return JSON.parse(localStorage.getItem('kreistakt-save'))}catch{return null}}
function cardText(c){return c.type==='num'?String(c.value):CARD_LABEL[c.type]}
function isSpecial(c){return c.type!=='num'||[1,4,7,8,13].includes(c.value)}
function teamOf(i){return i%2}
function partner(i){return (i+2)%4}
function addLog(t){state.log.unshift(t);state.log=state.log.slice(0,40)}
function occupied(pos,exclude=null){for(const p of state.players)for(const m of p.marbles)if(m!==exclude&&m.zone==='track'&&m.pos===pos)return m;return null}
function allMarbles(){return state.players.flatMap(p=>p.marbles)}
function playerDone(i){return state.players[i].marbles.every(m=>m.zone==='home')}
function activeOwners(i){return playerDone(i)?[partner(i)]:[i]}
function homeEntryDistance(m){const s=STARTS[m.owner];return (s-m.pos+64)%64}
function pathClear(from,steps,dir=1,exclude=null){for(let k=1;k<steps;k++){const p=(from+dir*k+640)%64;if(occupied(p,exclude))return false}return true}
function homeFree(owner,index){return !state.players[owner].marbles.some(m=>m.zone==='home'&&m.pos===index)}
function canEnterHome(m,steps){if(m.zone!=='track'||!m.lap)return false;const d=homeEntryDistance(m);if(d===0)return false;const idx=steps-d-1;if(idx<0||idx>3)return false;for(let i=0;i<=idx;i++)if(!homeFree(m.owner,i))return false;return true}
function normalMoves(owner,steps,dir=1){const out=[];for(const oi of activeOwners(owner))for(const m of state.players[oi].marbles){if(m.locked)continue;if(m.zone==='track'){
 if(dir===1&&canEnterHome(m,steps)){out.push({m,kind:'home',to:steps-homeEntryDistance(m)-1});continue}
 if(pathClear(m.pos,steps,dir,m))out.push({m,kind:'track',to:(m.pos+dir*steps+640)%64});
 } else if(m.zone==='home'&&dir===1){const to=m.pos+steps;if(to<=3&&Array.from({length:steps},(_,k)=>m.pos+k+1).every(x=>homeFree(m.owner,x)))out.push({m,kind:'home',to});}
 }return out}
function openingMoves(owner){const out=[];for(const oi of activeOwners(owner)){const m=state.players[oi].marbles.find(x=>x.zone==='yard');if(m)out.push({m,kind:'track',to:STARTS[oi],opening:true})}return out}
function applyMove(move,steps,desc='zieht'){
 const m=move.m; const before=JSON.parse(JSON.stringify(m)); let thrown=null;
 if(move.kind==='track'){thrown=occupied(move.to,m);if(thrown){const tb=JSON.parse(JSON.stringify(thrown));thrown.zone='yard';thrown.pos=null;thrown.lap=false;thrown.locked=false;move.thrown={ref:thrown,before:tb}}
 const old=m.pos;m.zone='track';m.pos=move.to;if(move.opening)m.lap=false;else if(old!==null){const dist=(move.to-old+64)%64;if(dist>0&&((old<STARTS[m.owner]&&move.to>=STARTS[m.owner])||(old>move.to&&STARTS[m.owner]===0)))m.lap=true;if(old===STARTS[m.owner])m.lap=true}
 } else {m.zone='home';m.pos=move.to;m.locked=move.to===3||Array.from({length:4-move.to},(_,k)=>move.to+k).every(i=>i===move.to||!homeFree(m.owner,i));}
 return {kind:'move',m,before,after:JSON.parse(JSON.stringify(m)),thrown:move.thrown,steps,desc};
}
function legalCards(i){return state.players[i].hand.filter(c=>canPlayCard(i,c))}
function canPlayCard(i,c){if(state.skip)return true;if(c.type==='num'){
 if([1,13].includes(c.value)&&openingMoves(i).length)return true;if(c.value===4)return normalMoves(i,4,-1).length>0;if(c.value===7)return sevenFirstMoves(i).length>0;if(c.value===8)return normalMoves(i,8,1).length>0||allMarbles().some(m=>m.zone==='track'&&activeOwners(i).includes(m.owner));return normalMoves(i,c.value,1).length>0}
 if(c.type==='trick')return state.players[i].marbles.some(m=>m.zone==='track')&&allMarbles().filter(m=>m.zone==='track').length>=2;
 if(c.type==='tac')return !!state.lastAction;
 if(c.type==='warrior')return state.players[i].marbles.some(m=>m.zone==='track');
 return true;
}
function sevenFirstMoves(i){return normalMoves(i,1,1)}
function deal(){state.dealNo++;state.dealer=(state.dealer+1)%4;const count=(state.deck.length>=24&&state.deck.length<44)?6:5; if(state.deck.length<count*4){state.deck=shuffle(state.deck.concat(state.discard));state.discard=[];state.dealNo=1}
 for(let r=0;r<count;r++)for(let k=1;k<=4;k++){const p=(state.dealer+k)%4;state.players[p].hand.push(state.deck.pop())}
 state.current=(state.dealer+1)%4;state.phase='announce';state.announcements=[];state.roundCards=count;state.exchange={choices:{}};addLog(`${state.names[state.dealer]} hat ${count} Karten gegeben.`);save();render();}
function startGame(){const names=COLORS.map((_,i)=>$('#n'+i).value.trim()||`Spieler ${i+1}`);state=fresh(names);save();deal()}
function showPass(next,callback){modal={type:'pass',next,callback};render()}
function announce(){const i=state.announcements.length;const can=state.players[i].hand.some(c=>c.type==='num'&&[1,13].includes(c.value));state.announcements.push(can);if(state.announcements.length<4)showPass(state.announcements.length,()=>{});else{state.phase='exchange';showPass(0,()=>{})}save();render()}
function chooseExchange(cardId){state.exchange.choices[state.current]=cardId;const next=(state.current+1)%4;if(Object.keys(state.exchange.choices).length<4){state.current=next;showPass(next,()=>{});}else{
 const incoming={};for(let i=0;i<4;i++){const card=state.players[i].hand.find(c=>c.id===state.exchange.choices[i]);incoming[partner(i)]=card}
 for(let i=0;i<4;i++)state.players[i].hand=state.players[i].hand.filter(c=>c.id!==state.exchange.choices[i]);for(let i=0;i<4;i++)state.players[i].hand.push(incoming[i]);state.phase='play';state.current=(state.dealer+1)%4;showPass(state.current,()=>{});addLog('Alle Spieler haben geheim eine Karte getauscht.');
 }save();render()}
function selectCard(id){selectedCard=state.players[state.current].hand.find(c=>c.id===id);render()}
function playSelected(){if(!selectedCard)return;const i=state.current,c=selectedCard;if(state.skip){finishCard(c,null,`${state.names[i]} setzt aus und legt ${cardText(c)} ab.`);state.skip=false;return}
 if(!canPlayCard(i,c)){toast('Diese Karte kann aktuell nicht regelgerecht gespielt werden.');return}
 if(c.type==='num'){if([1,13].includes(c.value)&&openingMoves(i).length){modal={type:'dual',card:c};render();return}if(c.value===8){modal={type:'eight',card:c};render();return}if(c.value===7){startSeven(c);return}const moves=normalMoves(i,c.value,c.value===4?-1:1);chooseMove(c,moves)}
 else if(c.type==='trick')startTrick(c);else if(c.type==='tac')playTac(c);else if(c.type==='angel')playAngel(c);else if(c.type==='devil')playDevil(c);else if(c.type==='warrior')playWarrior(c);else if(c.type==='fool')playFool(c);
}
function chooseMove(c,moves){modal={type:'moves',card:c,moves};render()}
function executeMove(c,idx){const mv=modal.moves[idx],act=applyMove(mv,c.value||1);finishCard(c,act,`${state.names[state.current]} spielt ${cardText(c)}.`)}
function startSeven(c){modal={type:'seven',card:c,left:7,actions:[]};render()}
function sevenStep(marbleId){const m=allMarbles().find(x=>x.id===marbleId);const owner=state.current;if(!activeOwners(owner).includes(m.owner))return;const move=normalMovesForSpecific(m,1,1)[0];if(!move)return;modal.actions.push(applyMove(move,1));modal.left--;if(modal.left===0){const acts=modal.actions;finishCard(modal.card,{kind:'multi',actions:acts},`${state.names[owner]} verteilt die 7.`)}else render()}
function normalMovesForSpecific(m,steps,dir){const fakeOwner=m.owner;const out=[];if(m.locked)return out;if(m.zone==='track'){if(dir===1&&canEnterHome(m,steps))out.push({m,kind:'home',to:steps-homeEntryDistance(m)-1});else if(pathClear(m.pos,steps,dir,m))out.push({m,kind:'track',to:(m.pos+dir*steps+640)%64})}else if(m.zone==='home'&&dir===1){const to=m.pos+steps;if(to<=3&&homeFree(m.owner,to))out.push({m,kind:'home',to})}return out}
function startTrick(c){modal={type:'trick',card:c,first:null};render()}
function trickPick(id){if(!modal.first){modal.first=id;render();return}if(modal.first===id)return;const a=allMarbles().find(m=>m.id===modal.first),b=allMarbles().find(m=>m.id===id);const beforeA=JSON.parse(JSON.stringify(a)),beforeB=JSON.parse(JSON.stringify(b));[a.pos,b.pos]=[b.pos,a.pos];const act={kind:'swap',a,b,beforeA,beforeB};finishCard(modal.card,act,`${state.names[state.current]} setzt den Trickser ein.`)}
function playTac(c){if(!state.lastAction){toast('Kein Zug zum Rückgängigmachen.');return}undoAction(state.lastAction.action);const inherited=state.lastAction.card;state.lastAction=null;state.players[state.current].hand=state.players[state.current].hand.filter(x=>x.id!==c.id);state.discard.push(c);selectedCard=null;modal=null;addLog(`${state.names[state.current]} spielt TAC und übernimmt ${cardText(inherited)}.`);selectedCard={...inherited,id:'tac-inherited-'+uid()};playSelected();}
function playAngel(c){const target=(state.current+1)%4;const opens=openingMoves(target).filter(x=>x.m.owner===target);if(opens.length){const act=applyMove(opens[0],1);finishCard(c,act,`${state.names[state.current]} spielt Engel für ${state.names[target]}.`)}else{const moves=[...normalMoves(target,1,1),...normalMoves(target,13,1)];if(!moves.length){finishCard(c,null,'Engel ohne mögliche Bewegung abgelegt.');return}modal={type:'angel',card:c,moves,target};render()}}
function angelMove(idx){const mv=modal.moves[idx];const act=applyMove(mv,1);finishCard(modal.card,act,`${state.names[state.current]} spielt Engel.`)}
function playDevil(c){const target=(state.current+1)%4;modal={type:'devil',card:c,target};render()}
function devilCard(id){const target=modal.target;const card=state.players[target].hand.find(x=>x.id===id);state.players[state.current].hand=state.players[state.current].hand.filter(x=>x.id!==modal.card.id);state.discard.push(modal.card);state.current=target;selectedCard=card;modal=null;addLog(`Der Teufel übernimmt den Zug von ${state.names[target]}.`);playSelected()}
function playWarrior(c){const own=state.players[state.current].marbles.filter(m=>m.zone==='track');modal={type:'warrior',card:c,own};render()}
function warriorPick(id){const m=allMarbles().find(x=>x.id===id);const others=allMarbles().filter(x=>x.zone==='track'&&x!==m).sort((a,b)=>((a.pos-m.pos+64)%64)-((b.pos-m.pos+64)%64));const t=others[0]||m;const beforeM=JSON.parse(JSON.stringify(m)),beforeT=JSON.parse(JSON.stringify(t));m.pos=t.pos;t.zone='yard';t.pos=null;t.lap=false;t.locked=false;finishCard(modal.card,{kind:'warrior',m,t,beforeM,beforeT},`${state.names[state.current]} spielt Krieger.`)}
function playFool(c){if(state.players[state.current].hand.length===1){finishCard(c,null,'Der Narr verfällt als letzte Karte.');return}const hands=state.players.map(p=>p.hand);for(let i=0;i<4;i++)state.players[(i+1)%4].hand=hands[i];const owner=state.current;state.players[owner].hand=state.players[owner].hand.filter(x=>x.id!==c.id);state.discard.push(c);selectedCard=null;modal=null;addLog(`${state.names[owner]} spielt den Narren: alle Hände wandern nach rechts.`);render()}
function finishCard(c,action,log){const i=state.current;state.players[i].hand=state.players[i].hand.filter(x=>x.id!==c.id);state.discard.push(c);if(action)state.lastAction={action,card:{...c,id:uid()},player:i};else state.lastAction=null;addLog(log);selectedCard=null;modal=null;checkWin();if(state.winner!==null){save();render();return}advance();}
function undoAction(a){if(!a)return;if(a.kind==='move'){Object.assign(a.m,a.before);if(a.thrown)Object.assign(a.thrown.ref,a.thrown.before)}else if(a.kind==='multi'){[...a.actions].reverse().forEach(undoAction)}else if(a.kind==='swap'){Object.assign(a.a,a.beforeA);Object.assign(a.b,a.beforeB)}else if(a.kind==='warrior'){Object.assign(a.m,a.beforeM);Object.assign(a.t,a.beforeT)}}
function advance(){const hands=state.players.map(p=>p.hand.length);if(hands.every(n=>n===0)){state.phase='deal';save();deal();return}state.current=(state.current+1)%4;save();showPass(state.current,()=>{});render()}
function checkWin(){for(let t=0;t<2;t++)if(TEAM[t].every(i=>playerDone(i))){state.winner=t;addLog(`Team ${t+1} gewinnt!`)}}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
function boardHTML(){let h='<div class="board">';[[7,7],[93,7],[7,93],[93,93]].forEach(([x,y])=>h+=`<div class="corner" style="left:${x}%;top:${y}%"></div>`);for(let i=0;i<64;i++){const a=(i/64)*Math.PI*2+Math.PI/2;const x=50+44*Math.cos(a),y=50+44*Math.sin(a);h+=`<div class="hole ${STARTS.includes(i)?'start':''}" style="left:${x}%;top:${y}%"></div>`}const homeAngles=[Math.PI/2,Math.PI,Math.PI*1.5,0];for(let p=0;p<4;p++)for(let k=0;k<4;k++){const a=homeAngles[p],r=31-k*7,x=50+r*Math.cos(a),y=50+r*Math.sin(a);h+=`<div class="home-hole" style="left:${x}%;top:${y}%"></div>`}
 for(const m of allMarbles()){let x,y;if(m.zone==='track'){const a=(m.pos/64)*Math.PI*2+Math.PI/2;x=50+44*Math.cos(a);y=50+44*Math.sin(a)}else if(m.zone==='home'){const a=homeAngles[m.owner],r=31-m.pos*7;x=50+r*Math.cos(a);y=50+r*Math.sin(a)}else continue;const selectable=modal&&((modal.type==='seven'&&activeOwners(state.current).includes(m.owner)&&normalMovesForSpecific(m,1,1).length)||(modal.type==='trick'&&m.zone==='track')||(modal.type==='warrior'&&m.owner===state.current&&m.zone==='track'));const fn=modal?.type==='seven'?`sevenStep('${m.id}')`:modal?.type==='trick'?`trickPick('${m.id}')`:modal?.type==='warrior'?`warriorPick('${m.id}')`:'';h+=`<div class="marble ${m.owner!==undefined?COLORS[m.owner]:''} ${selectable?'selectable':''}" onclick="${selectable?fn:''}" style="left:${x}%;top:${y}%"></div>`}return h+'</div>'}
function handHTML(){const p=state.players[state.current];return p.hand.map(c=>`<div class="card ${isSpecial(c)?'special':''} ${c.type!=='num'?'master':''} ${selectedCard?.id===c.id?'selected':''} ${!canPlayCard(state.current,c)?'disabled':''}" onclick="selectCard('${c.id}')">${cardText(c)}</div>`).join('')}
function setupHTML(){const saved=load();return `<div class="shell"><div class="panel setup"><h1>KreisTakt</h1><p>Private Tablet-Version für vier Spieler im Team.</p><div class="grid2">${COLORS.map((c,i)=>`<label class="field"><span><span class="dot ${c}" style="display:inline-block"></span> ${COLOR_NAMES[c]}</span><input id="n${i}" value="Spieler ${i+1}" maxlength="20"></label>`).join('')}</div><div class="team-card" style="margin-top:14px"><b>Team 1:</b> Blau + Rot<br><b>Team 2:</b> Grün + Schwarz</div><div class="actions"><button onclick="startGame()">Neues Spiel starten</button>${saved?'<button class="secondary" onclick="state=load();render()">Gespeichertes Spiel fortsetzen</button>':''}</div><details class="rules"><summary>Installation auf iPad/Android</summary><p>In Safari bzw. Chrome öffnen, Teilen-/Menü-Schaltfläche wählen und „Zum Home-Bildschirm“ bzw. „App installieren“ antippen.</p></details></div></div>`}
function mainHTML(){const p=state.players[state.current];return `<div class="shell"><div class="topbar"><div><div class="brand">KreisTakt</div><div class="small">Meisterversion · Autospeichern aktiv</div></div><div class="actions" style="margin:0"><button class="secondary" onclick="save();toast('Spiel gespeichert')">Speichern</button><button class="danger" onclick="if(confirm('Neues Spiel beginnen?')){localStorage.removeItem('kreistakt-save');state=null;render()}">Beenden</button></div></div><div class="game"><div class="panel board-wrap">${boardHTML()}</div><div class="sidebar"><div class="panel status"><div class="phase">${phaseText()}</div><div class="player-badge"><span class="dot ${p.color}"></span><b>${state.names[state.current]}</b> · ${COLOR_NAMES[p.color]}</div><div class="small">Team ${teamOf(state.current)+1} · Hand: ${p.hand.length} Karten · Stapel: ${state.deck.length}</div>${state.phase==='announce'?`<div class="actions"><button onclick="announce()">Meldung anzeigen</button></div>`:''}${state.phase==='play'?`<div class="actions"><button onclick="playSelected()" ${selectedCard?'':'disabled'}>Karte spielen</button><button class="secondary" onclick="discardUnused()" ${selectedCard?'':'disabled'}>Ungenutzt ablegen</button></div>`:''}</div>${state.phase==='exchange'?`<div class="panel hand"><p><b>Wähle genau eine Karte für ${state.names[partner(state.current)]}:</b></p>${p.hand.map(c=>`<div class="card ${isSpecial(c)?'special':''}" onclick="chooseExchange('${c.id}')">${cardText(c)}</div>`).join('')}</div>`:state.phase==='play'?`<div class="panel hand">${handHTML()}</div>`:''}<div class="panel log"><b>Spielprotokoll</b>${state.log.map(x=>`<div>• ${x}</div>`).join('')}</div></div></div>${overlayHTML()}${modalHTML()}</div>`}
function phaseText(){return state.phase==='announce'?'Melden: Kannst du eröffnen?':state.phase==='exchange'?'Geheimer Kartentausch':state.phase==='play'?'Karte wählen und Zug ausführen':'Karten werden gegeben'}
function overlayHTML(){if(state.winner!==null)return `<div class="overlay"><div class="overlay-card"><h2>Team ${state.winner+1} gewinnt!</h2><p>${TEAM[state.winner].map(i=>state.names[i]).join(' & ')}</p><button onclick="localStorage.removeItem('kreistakt-save');state=null;render()">Neues Spiel</button></div></div>`;if(!modal||modal.type!=='pass')return'';return `<div class="overlay"><div class="overlay-card"><div class="small" style="color:#ddd">Sichtschutz</div><h2>Tablet an ${state.names[modal.next]} weitergeben</h2><p>Die Handkarten bleiben verborgen.</p><button onclick="modal=null;render()">Ich bin ${state.names[modal.next]}</button></div></div>`}
function modalHTML(){if(!modal||modal.type==='pass')return'';let b='';if(modal.type==='dual')b=`<h2>${cardText(modal.card)} verwenden</h2><div class="choice-grid"><button onclick="chooseMove(modal.card,openingMoves(state.current))">Kugel eröffnen</button><button onclick="chooseMove(modal.card,normalMoves(state.current,modal.card.value,1))">${modal.card.value} Felder ziehen</button></div>`;else if(modal.type==='eight')b=`<h2>8 verwenden</h2><div class="choice-grid"><button onclick="chooseMove(modal.card,normalMoves(state.current,8,1))">8 Felder ziehen</button><button onclick="state.skip=true;finishCard(modal.card,null,'${state.names[state.current]} lässt den nächsten Spieler aussetzen.')">Nächsten aussetzen</button></div>`;else if(modal.type==='moves')b=`<h2>Kugel auswählen</h2><div class="choice-grid">${modal.moves.map((m,i)=>`<button onclick="executeMove(modal.card,${i})">${COLOR_NAMES[COLORS[m.m.owner]]}: Kugel ${m.m.id.split('-')[1]*1+1} → ${m.kind==='home'?'Haus '+(m.to+1):'Feld '+m.to}</button>`).join('')}</div>`;else if(modal.type==='seven')b=`<h2>Die 7 verteilen</h2><p>Noch <b>${modal.left}</b> Einzelschritte. Tippe auf eine gelb markierte Kugel.</p>`;else if(modal.type==='trick')b=`<h2>Trickser</h2><p>${modal.first?'Jetzt die zweite Kugel wählen.':'Erste Kugel auf dem Brett wählen.'}</p>`;else if(modal.type==='angel')b=`<h2>Engel</h2><div class="choice-grid">${modal.moves.map((m,i)=>`<button onclick="angelMove(${i})">${COLOR_NAMES[COLORS[m.m.owner]]} Kugel ${m.m.id.split('-')[1]*1+1}</button>`).join('')}</div>`;else if(modal.type==='devil')b=`<h2>Teufel</h2><p>Wähle eine Karte aus der Hand von ${state.names[modal.target]}.</p><div class="choice-grid">${state.players[modal.target].hand.map(c=>`<button onclick="devilCard('${c.id}')">${cardText(c)}</button>`).join('')}</div>`;else if(modal.type==='warrior')b=`<h2>Krieger</h2><p>Tippe auf eine eigene gelb markierte Kugel.</p>`;return `<div class="modal"><div class="modal-inner">${b}<div class="actions"><button class="secondary" onclick="modal=null;render()">Abbrechen</button></div></div></div>`}
function discardUnused(){if(!selectedCard)return;if(legalCards(state.current).length){toast('Wer kann, der muss: Es gibt einen möglichen Zug.');return}finishCard(selectedCard,null,`${state.names[state.current]} legt ${cardText(selectedCard)} ungenutzt ab.`)}
function render(){document.getElementById('app').innerHTML=state?mainHTML():setupHTML()}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
